services:
  frontend:
    image: node:18
    working_dir: /
    volumes:
      - ./FrontEnd:/
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  backend:
    image: node:18
    working_dir: /server
    volumes:
      - ./BackEnd:/server
    command: sh -c "npm install && npm run start"
    ports:
      - "8081:8081"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://yagelarbiv2:Ya123456@cluster0.vlxquk7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_PW=836faf02b09f121f2a4f2a469be32cd19b9b117ae035c40662c3ef6337c268c7
      - PORT=8081
      - NODE_ENV=development
      - TMDB_API_KEY=fc7f6503ba9049e513747fb6c5425a64
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yagelarbiv2
      - MONGO_INITDB_ROOT_PASSWORD=Ya123456

  auth-service:
    image: node:18
    working_dir: /server
    volumes:
      - ./MicroServices/Auth:/server
    command: sh -c "npm install && npm start"
    ports:
      - "5000:5000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://yagelarbiv2:Ya123456@cluster0.vlxquk7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_PW=836faf02b09f121f2a4f2a469be32cd19b9b117ae035c40662c3ef6337c268c7
      - PORT=5000
      - NODE_ENV=development
      - TMDB_API_KEY=fc7f6503ba9049e513747fb6c5425a64
      - EMAIL_USER_NAME=yagelarbiv3@gmail.com
      - EMAIL_PASSWORD=iimg ylzw gulx brqz
    depends_on:
      - mongo

  content-service:
    image: node:18
    working_dir: /server
    volumes:
      - ./MicroServices/Content:/server
    command: sh -c "npm install && npm run start"
    ports:
      - "6000:6000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://yagelarbiv2:Ya123456@cluster0.vlxquk7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_PW=836faf02b09f121f2a4f2a469be32cd19b9b117ae035c40662c3ef6337c268c7
      - PORT=6000
      - NODE_ENV=development
      - TMDB_API_KEY=fc7f6503ba9049e513747fb6c5425a64
    depends_on:
      - mongo